---
driver:
  name: vagrant

driver_config:
  require_chef_omnibus: true

platforms:
- name: ubuntu-12.04
- name: ubuntu-14.04
- name: centos-6.6
- name: centos-7.1

provisioner:
    name: chef_zero

suites:
- name: default
  run_list:
    - "recipe[victorops::default]"

- name: zabbix
  run_list:
    - "recipe[victorops::zabbix]"
