name             'victorops'
maintainer       'Nick Henry'
maintainer_email 'nshenry03@gmail.com'
license          'Apache 2.0'
description      'Installs/Configures victorops'
long_description 'Installs/Configures victorops'
version          '0.1.0'

depends          'apt'
depends          'yum'
